# Generated by Django 5.1.3 on 2025-01-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('summary', models.TextField()),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('graduation_year', models.IntegerField()),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('skills', models.TextField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('technologies', models.CharField(max_length=200)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('certification', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=150)),
                ('completion_date', models.DateField()),
                ('languages', models.TextField()),
            ],
        ),
    ]
